export default placesData = [
  {
    category_name: 'Palace',
    id: 0,
    place_address: 'City Place',
    place_audience: 'Youth',
    place_category: '1',
    place_date: '2023-04-24 09:48:14',
    place_description:
      '<p>City Place is situated in the heart of Jaipur. This place is very popular and sometimes crowdy as so many tourists visit this place often.&nbsp;</p>',
    place_featured: 'Yes',
    place_hours: '2',
    place_id: '1',
    place_image: 'https://fastly.picsum.photos/id/649/850/450.jpg?hmac=Lur-QIHD8zNuwJ-xKIF2aabqtJI2MsOklY1Vpd7-OF8',
    place_latitude: '24.579189',
    place_longitude: '73.683853',
    place_name: 'City Palace',
    place_phone: '555555555',
    place_type: '1',
    place_website: 'https://clientmeets.com/cityguide/',
    type_name: 'Tourism',
  },
  {
    category_name: 'Historical',
    id: 1,
    place_address: 'Jaipur',
    place_audience: 'Youth',
    place_category: '1',
    place_date: '2023-04-24 09:44:04',
    place_description:
      '<p>Amer Fort is in Jaipur city. It is center of attraction among foreigners.&nbsp;</p>',
    place_featured: 'Yes',
    place_hours: '2',
    place_id: '2',
    place_image: 'https://fastly.picsum.photos/id/1078/850/450.jpg?hmac=N9GoQ6GE7ys6Y0wwYl4Bsv3FzRFWpmogSAbEUJQHCwI',
    place_latitude: '26.988020',
    place_longitude: '75.852638',
    place_name: 'Amer Fort',
    place_phone: '8890180910',
    place_type: '1',
    place_website: 'https://clientmeets.com/cityguide/',
    type_name: 'Tourism',
  },
  {
    category_name: 'Palace',
    id: 0,
    place_address: 'City Place',
    place_audience: 'Youth',
    place_category: '1',
    place_date: '2023-04-24 09:48:14',
    place_description:
      '<p>City Place is situated in the heart of Jaipur. This place is very popular and sometimes crowdy as so many tourists visit this place often.&nbsp;</p>',
    place_featured: 'Yes',
    place_hours: '2',
    place_id: '3',
    place_image: 'https://fastly.picsum.photos/id/385/850/450.jpg?hmac=OPMlDduj8EOLr6I_9uVa0J6LozDJ_8HCJ58boSTt2So',
    place_latitude: '24.579189',
    place_longitude: '73.683853',
    place_name: 'City Palace',
    place_phone: '555555555',
    place_type: '1',
    place_website: 'https://clientmeets.com/cityguide/',
    type_name: 'Tourism',
  },
  {
    category_name: 'Historical',
    id: 1,
    place_address: 'Jaipur',
    place_audience: 'Youth',
    place_category: '1',
    place_date: '2023-04-24 09:44:04',
    place_description:
      '<p>Amer Fort is in Jaipur city. It is center of attraction among foreigners.&nbsp;</p>',
    place_featured: 'Yes',
    place_hours: '2',
    place_id: '4',
    place_image: 'https://fastly.picsum.photos/id/143/850/450.jpg?hmac=swLicvYv9eVMk1jj5JiLbA3XtsvVYumwf5-d-G7Iox4',
    place_latitude: '26.988020',
    place_longitude: '75.852638',
    place_name: 'Amer Fort',
    place_phone: '8890180910',
    place_type: '1',
    place_website: 'https://clientmeets.com/cityguide/',
    type_name: 'Tourism',
  },
  {
    category_name: 'Palace',
    id: 0,
    place_address: 'City Place',
    place_audience: 'Youth',
    place_category: '1',
    place_date: '2023-04-24 09:48:14',
    place_description:
      '<p>City Place is situated in the heart of Jaipur. This place is very popular and sometimes crowdy as so many tourists visit this place often.&nbsp;</p>',
    place_featured: 'Yes',
    place_hours: '2',
    place_id: '5',
    place_image: 'https://fastly.picsum.photos/id/863/850/450.jpg?hmac=oTZOUzTztNvqfvDcpAHGpjfV-1E72r3W8Bs6Qi05Mww',
    place_latitude: '24.579189',
    place_longitude: '73.683853',
    place_name: 'City Palace',
    place_phone: '555555555',
    place_type: '1',
    place_website: 'https://clientmeets.com/cityguide/',
    type_name: 'Tourism',
  },
  {
    category_name: 'Historical',
    id: 1,
    place_address: 'Jaipur',
    place_audience: 'Youth',
    place_category: '1',
    place_date: '2023-04-24 09:44:04',
    place_description:
      '<p>Amer Fort is in Jaipur city. It is center of attraction among foreigners.&nbsp;</p>',
    place_featured: 'Yes',
    place_hours: '2',
    place_id: '6',
    place_image: 'https://fastly.picsum.photos/id/1066/850/450.jpg?hmac=L1ufhTAouj_Yxdg94f81VW_13GhnZjrnVqp4XCb6oUY',
    place_latitude: '26.988020',
    place_longitude: '75.852638',
    place_name: 'Amer Fort',
    place_phone: '8890180910',
    place_type: '1',
    place_website: 'https://clientmeets.com/cityguide/',
    type_name: 'Tourism',
  },
  {
    category_name: 'Palace',
    id: 0,
    place_address: 'City Place',
    place_audience: 'Youth',
    place_category: '1',
    place_date: '2023-04-24 09:48:14',
    place_description:
      '<p>City Place is situated in the heart of Jaipur. This place is very popular and sometimes crowdy as so many tourists visit this place often.&nbsp;</p>',
    place_featured: 'Yes',
    place_hours: '2',
    place_id: '7',
    place_image: 'https://fastly.picsum.photos/id/649/850/450.jpg?hmac=Lur-QIHD8zNuwJ-xKIF2aabqtJI2MsOklY1Vpd7-OF8',
    place_latitude: '24.579189',
    place_longitude: '73.683853',
    place_name: 'City Palace',
    place_phone: '555555555',
    place_type: '1',
    place_website: 'https://clientmeets.com/cityguide/',
    type_name: 'Tourism',
  },
  {
    category_name: 'Historical',
    id: 1,
    place_address: 'Jaipur',
    place_audience: 'Youth',
    place_category: '1',
    place_date: '2023-04-24 09:44:04',
    place_description:
      '<p>Amer Fort is in Jaipur city. It is center of attraction among foreigners.&nbsp;</p>',
    place_featured: 'Yes',
    place_hours: '2',
    place_id: '8',
    place_image: 'https://fastly.picsum.photos/id/1078/850/450.jpg?hmac=N9GoQ6GE7ys6Y0wwYl4Bsv3FzRFWpmogSAbEUJQHCwI',
    place_latitude: '26.988020',
    place_longitude: '75.852638',
    place_name: 'Amer Fort',
    place_phone: '8890180910',
    place_type: '1',
    place_website: 'https://clientmeets.com/cityguide/',
    type_name: 'Tourism',
  },
  {
    category_name: 'Palace',
    id: 0,
    place_address: 'City Place',
    place_audience: 'Youth',
    place_category: '1',
    place_date: '2023-04-24 09:48:14',
    place_description:
      '<p>City Place is situated in the heart of Jaipur. This place is very popular and sometimes crowdy as so many tourists visit this place often.&nbsp;</p>',
    place_featured: 'Yes',
    place_hours: '2',
    place_id: '9',
    place_image: 'https://fastly.picsum.photos/id/385/850/450.jpg?hmac=OPMlDduj8EOLr6I_9uVa0J6LozDJ_8HCJ58boSTt2So',
    place_latitude: '24.579189',
    place_longitude: '73.683853',
    place_name: 'City Palace',
    place_phone: '555555555',
    place_type: '1',
    place_website: 'https://clientmeets.com/cityguide/',
    type_name: 'Tourism',
  },
  {
    category_name: 'Historical',
    id: 1,
    place_address: 'Jaipur',
    place_audience: 'Youth',
    place_category: '1',
    place_date: '2023-04-24 09:44:04',
    place_description:
      '<p>Amer Fort is in Jaipur city. It is center of attraction among foreigners.&nbsp;</p>',
    place_featured: 'Yes',
    place_hours: '2',
    place_id: '10',
    place_image: 'https://fastly.picsum.photos/id/143/850/450.jpg?hmac=swLicvYv9eVMk1jj5JiLbA3XtsvVYumwf5-d-G7Iox4',
    place_latitude: '26.988020',
    place_longitude: '75.852638',
    place_name: 'Amer Fort',
    place_phone: '8890180910',
    place_type: '1',
    place_website: 'https://clientmeets.com/cityguide/',
    type_name: 'Tourism',
  },
  {
    category_name: 'Palace',
    id: 0,
    place_address: 'City Place',
    place_audience: 'Youth',
    place_category: '1',
    place_date: '2023-04-24 09:48:14',
    place_description:
      '<p>City Place is situated in the heart of Jaipur. This place is very popular and sometimes crowdy as so many tourists visit this place often.&nbsp;</p>',
    place_featured: 'Yes',
    place_hours: '2',
    place_id: '2',
    place_image: 'https://fastly.picsum.photos/id/863/850/450.jpg?hmac=oTZOUzTztNvqfvDcpAHGpjfV-1E72r3W8Bs6Qi05Mww',
    place_latitude: '24.579189',
    place_longitude: '73.683853',
    place_name: 'City Palace',
    place_phone: '555555555',
    place_type: '11',
    place_website: 'https://clientmeets.com/cityguide/',
    type_name: 'Tourism',
  },
  {
    category_name: 'Historical',
    id: 1,
    place_address: 'Jaipur',
    place_audience: 'Youth',
    place_category: '1',
    place_date: '2023-04-24 09:44:04',
    place_description:
      '<p>Amer Fort is in Jaipur city. It is center of attraction among foreigners.&nbsp;</p>',
    place_featured: 'Yes',
    place_hours: '2',
    place_id: '12',
    place_image: 'https://fastly.picsum.photos/id/1066/850/450.jpg?hmac=L1ufhTAouj_Yxdg94f81VW_13GhnZjrnVqp4XCb6oUY',
    place_latitude: '26.988020',
    place_longitude: '75.852638',
    place_name: 'Amer Fort',
    place_phone: '8890180910',
    place_type: '1',
    place_website: 'https://clientmeets.com/cityguide/',
    type_name: 'Tourism',
  },
];

export const placeCategories = [
  {
    id: 1,
    place_category_id: '1',
    place_category_image:
      'https://fastly.picsum.photos/id/1012/80/80.jpg?hmac=sXWdCgcRv_OV7jWJDbzOIfjm1wdVASE3r-6BGABdCKc',
    place_category_name: 'Historical',
  },
  {
    id: 2,
    place_category_id: '1',
    place_category_image:
      'https://fastly.picsum.photos/id/236/80/80.jpg?hmac=FWUuEKc8dAd_GIJOSIwpV8HjV71bhCkQUaVOOr_w2ow',
    place_category_name: 'Monuments',
  },
  {
    id: 3,
    place_category_id: '1',
    place_category_image:
      'https://fastly.picsum.photos/id/918/80/80.jpg?hmac=nX0-rZwMAtjP1Kr0D4g6gssvAdxZfvXKhXNx8Y__BQE',
    place_category_name: 'Artificial',
  },
  {
    id: 4,
    place_category_id: '1',
    place_category_image:
      'https://fastly.picsum.photos/id/206/80/80.jpg?hmac=PVuTHhe1AzSItaU0paANoNziZHYb4EZf_ivf7ONdJNY',
    place_category_name: 'Place Category 1',
  },
  {
    id: 4,
    place_category_id: '1',
    place_category_image:
      'https://fastly.picsum.photos/id/654/80/80.jpg?hmac=W69eU9ApqZ-w5jps-3Xd4bY0FxXGLx88PPLV7DsVors',
    place_category_name: 'Place Category 2',
  },
  {
    id: 4,
    place_category_id: '1',
    place_category_image:
      'https://fastly.picsum.photos/id/623/80/80.jpg?hmac=a8j-UrPBO9OG8fuf8-WnQbkbXqnOwVRvC8LDTHBeZv8',
    place_category_name: 'Place Category 3',
  },
  {
    id: 4,
    place_category_id: '1',
    place_category_image:
      'https://fastly.picsum.photos/id/967/80/80.jpg?hmac=Ue6XrnekICkGYko3dIUkKtQqwKnvvne1dv2Ztdv0v9Y',
    place_category_name: 'Place Category 4',
  },
  {
    id: 4,
    place_category_id: '1',
    place_category_image:
      'https://fastly.picsum.photos/id/1064/80/80.jpg?hmac=dNFPVuqJaEivKIcBl55zH8K_b8ZO32bGIRmdA3M4-B8',
    place_category_name: 'Place Category 5',
  },
  {
    id: 4,
    place_category_id: '1',
    place_category_image:
      'https://fastly.picsum.photos/id/896/80/80.jpg?hmac=VjkvafiMHPLCrBCIGnNIA84xDRGDP00DiRjgUpHap8g',
    place_category_name: 'Place Category 6',
  },
  {
    id: 4,
    place_category_id: '1',
    place_category_image:
      'https://fastly.picsum.photos/id/402/80/80.jpg?hmac=cOzdPBffSOKmr68i5a1VEzgcrcNmS00O_PTCnJxyg_4',
    place_category_name: 'Place Category 7',
  },
  {
    id: 4,
    place_category_id: '1',
    place_category_image:
      'https://fastly.picsum.photos/id/548/80/80.jpg?hmac=YlumY0ukfJpIBxmKpRHoPrTXe530U_lNZQfuGlksBjQ',
    place_category_name: 'Place Category 8',
  },
  {
    id: 4,
    place_category_id: '1',
    place_category_image:
      'https://fastly.picsum.photos/id/654/80/80.jpg?hmac=W69eU9ApqZ-w5jps-3Xd4bY0FxXGLx88PPLV7DsVors',
    place_category_name: 'Place Category 9',
  },
];

export const categoryByType = [
  {
    id: 0,
    place_type_category: '1',
    place_type_id: '1',
    place_type_image:
      'https://fastly.picsum.photos/id/548/80/80.jpg?hmac=YlumY0ukfJpIBxmKpRHoPrTXe530U_lNZQfuGlksBjQ',
    place_type_name: 'Tourism',
  },
  {
    id: 0,
    place_type_category: '1',
    place_type_id: '1',
    place_type_image:
      'https://fastly.picsum.photos/id/630/80/80.jpg?hmac=6D6omW1bG6MVDTgH4Y377_083Vj-77YJowV41qEI8Ow',
    place_type_name: 'Temples',
  },
  {
    id: 0,
    place_type_category: '1',
    place_type_id: '1',
    place_type_image:
      'https://fastly.picsum.photos/id/4/80/80.jpg?hmac=B2_yPW-O_pl7NIH_9LqcteiBMSOJuFhGk88Ld5YhDgA',
    place_type_name: 'Luxury',
  },
  {
    id: 0,
    place_type_category: '1',
    place_type_id: '1',
    place_type_image:
      'https://fastly.picsum.photos/id/1038/80/80.jpg?hmac=cKg3eahhKR6mVqf6xmvaU6F7uKCdkHLqdeXDhwJ47iY',
    place_type_name: 'Photography',
  },
  {
    id: 0,
    place_type_category: '1',
    place_type_id: '1',
    place_type_image:
      'https://fastly.picsum.photos/id/581/80/80.jpg?hmac=c7OGQJZZti2xyzs9rm-PkR_4jl70wABbW-6-IxYYacI',
    place_type_name: 'Mountains',
  },
];

export const placesByCategory = [
  {
    category_name: 'Palace',
    id: 0,
    place_address: 'City Place',
    place_audience: 'Youth',
    place_category: '1',
    place_date: '2023-04-24 09:48:14',
    place_description:
      '<p>City Place is situated in the heart of Jaipur. This place is very popular and sometimes crowdy as so many tourists visit this place often.&nbsp;</p>',
    place_featured: 'Yes',
    place_hours: '2',
    place_id: '2',
    place_image: 'https://fastly.picsum.photos/id/649/850/450.jpg?hmac=Lur-QIHD8zNuwJ-xKIF2aabqtJI2MsOklY1Vpd7-OF8',
    place_latitude: '24.579189',
    place_longitude: '73.683853',
    place_name: 'City Palace',
    place_phone: '555555555',
    place_type: '1',
    place_website: 'https://clientmeets.com/cityguide/',
    type_name: 'Tourism',
  },
  {
    category_name: 'Historical',
    id: 1,
    place_address: 'Jaipur',
    place_audience: 'Youth',
    place_category: '1',
    place_date: '2023-04-24 09:44:04',
    place_description:
      '<p>Amer Fort is in Jaipur city. It is center of attraction among foreigners.&nbsp;</p>',
    place_featured: 'Yes',
    place_hours: '2',
    place_id: '1',
    place_image: 'https://fastly.picsum.photos/id/1078/850/450.jpg?hmac=N9GoQ6GE7ys6Y0wwYl4Bsv3FzRFWpmogSAbEUJQHCwI',
    place_latitude: '26.988020',
    place_longitude: '75.852638',
    place_name: 'Amer Fort',
    place_phone: '8890180910',
    place_type: '1',
    place_website: 'https://clientmeets.com/cityguide/',
    type_name: 'Tourism',
  },
  {
    category_name: 'Palace',
    id: 0,
    place_address: 'City Place',
    place_audience: 'Youth',
    place_category: '1',
    place_date: '2023-04-24 09:48:14',
    place_description:
      '<p>City Place is situated in the heart of Jaipur. This place is very popular and sometimes crowdy as so many tourists visit this place often.&nbsp;</p>',
    place_featured: 'Yes',
    place_hours: '2',
    place_id: '2',
    place_image: 'https://fastly.picsum.photos/id/385/850/450.jpg?hmac=OPMlDduj8EOLr6I_9uVa0J6LozDJ_8HCJ58boSTt2So',
    place_latitude: '24.579189',
    place_longitude: '73.683853',
    place_name: 'City Palace',
    place_phone: '555555555',
    place_type: '1',
    place_website: 'https://clientmeets.com/cityguide/',
    type_name: 'Tourism',
  },
  {
    category_name: 'Historical',
    id: 1,
    place_address: 'Jaipur',
    place_audience: 'Youth',
    place_category: '1',
    place_date: '2023-04-24 09:44:04',
    place_description:
      '<p>Amer Fort is in Jaipur city. It is center of attraction among foreigners.&nbsp;</p>',
    place_featured: 'Yes',
    place_hours: '2',
    place_id: '1',
    place_image: 'https://fastly.picsum.photos/id/143/850/450.jpg?hmac=swLicvYv9eVMk1jj5JiLbA3XtsvVYumwf5-d-G7Iox4',
    place_latitude: '26.988020',
    place_longitude: '75.852638',
    place_name: 'Amer Fort',
    place_phone: '8890180910',
    place_type: '1',
    place_website: 'https://clientmeets.com/cityguide/',
    type_name: 'Tourism',
  },
  {
    category_name: 'Palace',
    id: 0,
    place_address: 'City Place',
    place_audience: 'Youth',
    place_category: '1',
    place_date: '2023-04-24 09:48:14',
    place_description:
      '<p>City Place is situated in the heart of Jaipur. This place is very popular and sometimes crowdy as so many tourists visit this place often.&nbsp;</p>',
    place_featured: 'Yes',
    place_hours: '2',
    place_id: '2',
    place_image: 'https://fastly.picsum.photos/id/863/850/450.jpg?hmac=oTZOUzTztNvqfvDcpAHGpjfV-1E72r3W8Bs6Qi05Mww',
    place_latitude: '24.579189',
    place_longitude: '73.683853',
    place_name: 'City Palace',
    place_phone: '555555555',
    place_type: '1',
    place_website: 'https://clientmeets.com/cityguide/',
    type_name: 'Tourism',
  },
  {
    category_name: 'Historical',
    id: 1,
    place_address: 'Jaipur',
    place_audience: 'Youth',
    place_category: '1',
    place_date: '2023-04-24 09:44:04',
    place_description:
      '<p>Amer Fort is in Jaipur city. It is center of attraction among foreigners.&nbsp;</p>',
    place_featured: 'Yes',
    place_hours: '2',
    place_id: '1',
    place_image: 'https://fastly.picsum.photos/id/1066/850/450.jpg?hmac=L1ufhTAouj_Yxdg94f81VW_13GhnZjrnVqp4XCb6oUY',
    place_latitude: '26.988020',
    place_longitude: '75.852638',
    place_name: 'Amer Fort',
    place_phone: '8890180910',
    place_type: '1',
    place_website: 'https://clientmeets.com/cityguide/',
    type_name: 'Tourism',
  },
];

export const offersData = [
  {
    category_name: 'Coupons',
    id: 0,
    offer_category: '1',
    offer_description: '<p>New Coupons Arrived !!!</p>',
    offer_featured: 'Yes',
    offer_id: '1',
    offer_image: 'offer_1682329848.jpg',
    offer_oldprice: '20',
    offer_price: '10',
    offer_terms: '<p>New Coupons Arrived !!!</p>',
    offer_title: 'New Coupons Arrived !!!',
    save: 10,
  },
  {
    category_name: 'Coupons',
    id: 1,
    offer_category: '1',
    offer_description: '<p>New Coupons Arrived !!!</p>',
    offer_featured: 'Yes',
    offer_id: '1',
    offer_image: 'offer_1682329848.jpg',
    offer_oldprice: '20',
    offer_price: '10',
    offer_terms: '<p>New Coupons Arrived !!!</p>',
    offer_title: 'New Coupons Arrived !!!',
    save: 10,
  },
];

export const newsData = [
  {
    category_name: 'News',
    id: 0,
    news_category: '1',
    news_date: '24/04/23',
    news_description: '<p>App Updates</p>',
    news_id: '1',
    news_image: 'post_1682329935.jpg',
    news_status: 'Published',
    news_title: 'App Updates',
  },
];

// export const offersCategoriesScreen = OffersCategoriesScreen